-- PART 1:
 
CREATE TABLE COURSE_INFO (
	COURSE_CODE int,
	COURSE varchar(20),
	COURSE_DESCRIPTION varchar(20),
	COURSE_START_DATE Date
);

-- PART 2:
 
ALTER TABLE COURSE_INFO
  MODIFY (COURSE_CODE varchar(20),
  COURSE_DESCRIPTION varchar(200));


ALTER TABLE COURSE_INFO
	ADD (Course_Duration int,
  Number_of_Participants Number(9,0),	
  Course_Type char(3));

ALTER TABLE COURSE_INFO
	RENAME COLUMN COURSE TO COURSE_NAME;

-- PART 3:
 
ALTER TABLE COURSE_INFO
	RENAME TO CMS_COURSE_INFO;

TRUNCATE TABLE CMS_COURSE_INFO;
DROP TABLE CMS_COURSE_INFO;

-- PART 4:
 
CREATE TABLE COURSE_INFO (
	COURSE_CODE int,
	COURSE_NAME varchar(20),
	COURSE_DESCRIPTION varchar(20),
	COURSE_START_DATE Date
);             
         
INSERT ALL
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (343, 'Java Programming', 'Basics of Java', TO_DATE('12/12/2012 09:00:00', 'mm/dd/yyyy hh24:mi:ss'))
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (167, 'C Programming', 'Basics of C', TO_DATE('11/11/2012 09:00:00', 'mm/dd/yyyy hh24:mi:ss'))
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (347, 'RDBMS', 'Basics of RDBMS', TO_DATE(NULL))
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (106, 'Oracle', 'Oracle SQL', TO_DATE('11/03/2011 09:00:00', 'mm/dd/yyyy hh24:mi:ss' ))
SELECT * FROM DUAL;

-- PART 5:
 
UPDATE COURSE_INFO 
SET COURSE_NAME = 'MYSQL',
    COURSE_DESCRIPTION = 'MySQL'
    WHERE COURSE_CODE = 106;

DELETE FROM COURSE_INFO 
    WHERE COURSE_NAME = 'RDBMS';

--  PART 6:

INSERT ALL
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (106, 'Oracle', 'Oracle PL SQL', TO_DATE('11/03/2011 09:00:00', 'mm/dd/yyyy hh24:mi:ss'))
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (302, 'Oracle', 'Oracle Architecture', TO_DATE('11/04/2011 09:00:00', 'mm/dd/yyyy hh24:mi:ss'))
INTO COURSE_INFO(COURSE_CODE, COURSE_NAME, COURSE_DESCRIPTION, COURSE_START_DATE)
VALUES (231, 'Core Java', 'Java IO', TO_DATE('11/06/2011 09:00:00', 'mm/dd/yyyy hh24:mi:ss'))
SELECT * FROM DUAL;


SELECT * FROM COURSE_INFO
WHERE COURSE_NAME = 'Core Java';

SELECT * FROM COURSE_INFO
WHERE COURSE_NAME = 'Core Java' OR COURSE_CODE = 343;

SELECT COURSE_NAME FROM COURSE_INFO;